name: extended_mobile
description: Extended mobile app (Flutter) - initial scaffold
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  flutter_secure_storage: ^9.2.2
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  flutter_dotenv: ^5.1.0
  web_socket_channel: ^2.4.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.2.2
  flutter_cache_manager: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/env
    - assets/env.example


